version: '3'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG: ./log
    volumes:
      - /var/log/bte:/home/node/app/log
  redis:
    container_name: bte_redis
    restart: always
    image: "redis:alpine"
    ports:
      - '6379:6379'
    volumes:
      - ./.redis.conf:/usr/local/etc/redis/redis.conf
